### ISSUE TITLE
How-To: USB license dongle in readme docu

### ISSUE THREAD

**Issue by Janhsen** [HilscherAutomation/netPI-codesys-basis#1]
Add usb dongle support in readme. The runtime license is not stored in the docker image in this case, but on the dongle. 

USB dongle has to be plugged in netPI before deploying new docker image.

Map dev/hidraw0 to container dev/hidraw0 (assuming, that there is no other input device). 

Could save some other users some time, to figure out what to do, to get the dongle working in the container.

**Comment by hilschernetpi** [comment]
Yes good remark. I am anyway releasing a new version of the repo for supporting V3.5.15.x version tomorrow. So I will add your comment

**Comment by hilschernetpi** [comment]
new version uploaded right now. Readme extended by this function
